version: '3.5'

services:
  mc_server:
    build:
      context: ./server
    container_name: mc_server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

    env_file:
      - ./server/server.env
    ports:
      - 3050:3050
    depends_on:
      - mc_db
    command: ['nodemon', 'index.js']

  mc_db:
    image: mongo:latest
    container_name: mc_db
    volumes:
      - ./docker/data/mc_db:/data/db
